Feature/button
isdi-coders-2023/coding-adventure-Diana-Vidal-front-202301-BCN pull request #1
Opened 2023-02-27 15:44 UTC by dvidaal

2023-02-27 16:09 UTC, bertoforteza requested changes

2023-02-27 16:09 UTC, bertoforteza commented on src/components/Button/ButtonStyled.tsx
> +  color: #1e1e1e;
Puedes poner los colores, font-sizes y fuentes en variables? También podrías probar de usar un `ThemeProvider`

2023-02-28 08:54 UTC, dvidaal commented on src/components/Button/ButtonStyled.tsx
> +  color: #1e1e1e;
Actualizado Berto, he usado ThemeProvider.

2023-02-28 14:55 UTC, bertoforteza commented on src/components/Button/ButtonStyled.tsx
> +  color: #1e1e1e;
Perfecto Diana

2023-02-28 14:55 UTC, bertoforteza approved these changes

2023-02-28 14:56 UTC, merged